name: mobility_generation
channels:
  - pytorch
  - nvidia
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pygeos
  - geopandas=0.14.4
  - trackintel=1.3.1
  - gensim
  - easydict
  - pyyaml
  - pytorch=2.3.1
  - torchvision==0.18.1 
  - torchaudio==2.3.1
  - pytorch-cuda=11.8
  - transformers=4.41.2
  - blobfile
  - wandb
  - datasets
