name: generation
channels:
  - pytorch
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pygeos=0.12.0
  - pytorch
  - geopandas
  - gensim
  - tqdm
  - easydict
  - pyyaml
  - transformers
  - cudatoolkit=11.3
  - trackintel
