misc:
  dataset: mobis

  level: "10_13"
  split: "train"

  # seq_len: 512
  # 14882 + 1 for seperation
  max_location: 14883

  seed: 101
  # 
  neighbors: 12
  # 
  negative_num: 20
  
  batch_size: 128
  log_interval: 20
  num_workers: 0

embedding:
  hidden_dim: 128

model:
  networkName: skip-pre

optimiser:
  lr: 0.005
  weight_decay: 0

dataset:
  data_dir: ./data/diff
  save_root: ./runs