misc:
  dataset: mobis

  wandb_name: test
  split: train
  dataset_variation: tiny
  level: "10_13"
  src_min_days: 14
  tgt_min_days: 7

  # seq_len: 512
  # 14882 + 1 (28743 + 1) for seperation
  max_location: 14883 # 28744, 14883

  seed: 101
  # 
  if_embed_xy: False
  if_embed_poi: False
  if_diffuse_duration: False
  
  batch_size: 512
  microbatch: 32
  log_interval: 10
  num_workers: 16
  
fp16:
  use_fp16: True


embedding:
  pre_train_embed: None #./data/matrix/loc_embedding.pk
  hidden_dim: 128
  poi_dim: 32

diffusion:
  networkName: diffseq
  predict_xstart: True
  rescale_timesteps: True
  diffusion_steps: 2000
  noise_schedule: sqrt
  schedule_sampler: lossaware
  rescaling_factor: 4

  learned_mean_embed: True
  emb_scale_factor: 1.0
  denoise: True
  denoise_rate: 0.5
  rejection_rate: 0.0
  reg_rate: 0.0
  device: ""
  data_split_num: 0

  timestep_respacing: ""

model:
  # 
  num_encoder_layers: 2
  hidden_size: 768
  num_attention_heads: 12
  dropout: 0.1



optimiser:
  lr: 0.0001
  weight_decay: 0.01
  ema_rate: 0.9999
  gradient_clipping: 3

  # for warmup
  warmup_epochs: 3
  decay_epochs: 0

  # training
  max_epochs: 120
  save_epochs: 2

  # 
  load_checkpoint: False
  checkpoint_path: ./runs/mobis_diffseq_17165500
  load_opt: True

dataset:
  data_dir: ./data/diff
  save_root: ./runs

  # data_dir: /cluster/scratch/hongy/generation/data/diff
  # save_root: /cluster/scratch/hongy/generation/runs