misc:
  dataset: mobis

  wandb_name: test
  split: train
  dataset_variation: tiny 
  level: 14
  src_min_days: 14
  tgt_min_days: 7

  # seq_len: 512
  # 14882 -> 14976 (28742 -> 28800)
  max_location: 28800  # 28800, 14976
  max_mode: 8  # 7+1 padding

  seed: 101
  # 
  if_embed_context: False
  if_include_duration: False
  if_include_mode: True
  
  batch_size: 512
  microbatch: 64
  log_interval: 5
  num_workers: 0
  
fp16:
  use_fp16: True


embedding:
  pre_train_embed: None #./data/matrix/loc_embedding.pk
  input_dims: 128
  poi_dim: 32

sampler:
  schedule_sampler: lossaware

diffusion:
  networkName: na
  rescale_timesteps: True
  diffusion_steps: 2000
  noise_schedule: sqrt
  rescaling_factor: 1

  rounding_loss: True
  self_cond: False

  decoding_steps: 20
  decoding_noise_schedule: sqrt
  decoding_rescaling_factor: 1
  clamping: False

model:
  # 
  num_layers: 6
  hidden_size: 512
  num_attention_heads: 8
  dropout: 0.1



optimiser:
  lr: 0.0006
  weight_decay: 0.01
  ema_rate: 0.9999
  gradient_clipping: 1

  # for warmup
  warmup_epochs: 3
  decay_epochs: 200

  # training
  max_epochs: 200
  save_epochs: 5

  # 
  load_checkpoint: False
  checkpoint_path: ./runs/mobis_na_all_layer2_cond_13
  load_opt: True

dataset:
  data_dir: ./data/diff
  save_root: ./runs

  # data_dir: /cluster/scratch/hongy/generation/data/diff
  # save_root: /cluster/scratch/hongy/generation/runs