misc:
  dataset: mobis

  wandb_name: test
  split: train
  dataset_variation: all
  level: "10_13"
  src_min_days: 14
  tgt_min_days: 7

  # seq_len: 512
  # 14882 + 1 for seperation
  max_location: 14883

  seed: 101
  # 
  if_embed_time: False
  if_embed_user: False
  if_embed_poi: False
  if_embed_duration: False
  
  batch_size: 256
  microbatch: 32
  log_interval: 100
  num_workers: 0
  
fp16:
  use_fp16: True


embedding:
  hidden_dim: 128
  hidden_t_dim: 128

diffusion:
  networkName: diffseq
  predict_xstart: True
  rescale_timesteps: True
  diffusion_steps: 2000
  noise_schedule: sqrt
  schedule_sampler: lossaware

  learned_mean_embed: True
  emb_scale_factor: 1.0
  denoise: True
  denoise_rate: 0.5
  rejection_rate: 0.0
  reg_rate: 0.0
  device: ""
  data_split_num: 0

  timestep_respacing: ""

model:
  # 
  num_encoder_layers: 6
  dropout: 0.1



optimiser:
  lr: 0.0005
  weight_decay: 0
  ema_rate: 0.9999
  gradient_clipping: 3
  # for loss
  # loss_weight: 0.1

  # for warmup
  warmup_epochs: 3
  decay_epochs: 0
  # for early stop
  early_stop_patience: 3
  early_stop_gamma: 0.15

dataset:
  data_dir: ./data/diff
  save_root: ./runs

  # data_dir: /cluster/scratch/hongy/generation/data/diff
  # save_root: /cluster/scratch/hongy/generation/runs