misc:
  dataset: mobis

  level: "10_13"
  src_min_days: 14
  tgt_min_days: 7

  seq_len: 512
  max_location: 14882

  seed: 101
  # 
  if_embed_time: False
  if_embed_user: False
  if_embed_poi: False
  if_embed_duration: False

  verbose: True
  debug: False
  use_fp16: False
  fp16_scale_growth: 0.001
  batch_size: 128
  microbatch: 16
  log_interval: 10
  num_workers: 0
  

embedding:
  hidden_dim: 128
  hidden_t_dim: 128

  base_emb_size: 64
  poi_original_size: 16

diffusion:
  networkName: diffseq
  predict_xstart: True
  rescale_timesteps: True
  diffusion_steps: 2000
  noise_schedule: sqrt
  schedule_sampler: lossaware

  timestep_respacing: ""

model:
  model_name: "bert-base-uncased"
  # 
  num_encoder_layers: 2
  nhead: 4
  dim_feedforward: 128
  dropout: 0.1



optimiser:
  max_epoch: 100
  lr: 0.001
  weight_decay: 0.000001
  ema_rate: 0.9999
  gradient_clipping: -1.0
  # for loss
  loss_weight: 0.1

  # for warmup
  num_warmup_epochs: 2
  num_training_epochs: 50
  # for decay
  patience: 3
  lr_step_size: 1
  lr_gamma: 0.1

dataset:
  data_dir: ./data/diff
  save_root: ./runs


# {
#   "vocab": "bert",
#   "vocab_size": 0,
#   ,
#   "notes": "folder-notes",
#   "checkpoint_path": "diffusion_models",
#   "seq_len": 128,
#   "seed": 101,
#   "use_kl": false,
#   "emb_scale_factor": 1.0
# }