misc:
  dataset: mobis

  wandb_name: all_full_run
  split: train
  dataset_variation: all
  level: "10_13"
  src_min_days: 14
  tgt_min_days: 7

  # seq_len: 512
  max_location: 14882

  seed: 101
  # 
  if_embed_time: False
  if_embed_user: False
  if_embed_poi: False
  if_embed_duration: False
  
  batch_size: 128
  microbatch: 32
  log_interval: 100
  num_workers: 0
  
fp16:
  use_fp16: False
  fp16_scale_growth: 0.001


embedding:
  hidden_dim: 128
  hidden_t_dim: 128

diffusion:
  networkName: diffseq
  predict_xstart: True
  rescale_timesteps: True
  diffusion_steps: 2000
  noise_schedule: sqrt
  schedule_sampler: lossaware

  timestep_respacing: ""

model:
  # 
  num_encoder_layers: 2
  dropout: 0.1



optimiser:
  lr: 0.001
  weight_decay: 0.000001
  ema_rate: 0.9999
  gradient_clipping: 1
  # for loss
  # loss_weight: 0.1

  # for warmup
  warmup_epochs: 1
  decay_epochs: 100
  # for early stop
  early_stop_patience: 3
  early_stop_gamma: 0.1

dataset:
  # data_dir: ./data/diff
  # save_root: ./runs

  data_dir: /cluster/scratch/hongy/generation/data/diff
  save_root: /cluster/scratch/hongy/generation/runs