misc:
  dataset: mobis


  dataset_variation: all
  level: 13
  src_min_days: 14
  tgt_min_days: 7

  # normal
  clamping: False
  decoding_steps: 200
  decoding_rescaling_factor: 1
  # DPM
  # clip_denoised: False
  # clamp: False
  # step: 20
  # start_n: 0
  # 
  split: test

  model_path: ./runs/mobis_na_13
  trained_model_name: model_ema_150.pt
  pre_train_embed: None # ./data/matrix/loc_embedding.pk

  # seq_len: 512
  # max_location: 14883

  seed: 101
  
  batch_size: 256
  num_workers: 0

dataset:
  data_dir: ./data/diff
  save_root: ./runs