misc:
  dataset: mobis

  wandb_name: test
  split: train
  dataset_variation: tiny
  level: "10_13"
  src_min_days: 14
  tgt_min_days: 7

  # seq_len: 512
  # 14882 + 1 for seperation
  max_location: 14883

  seed: 101
  # 
  if_embed_xy: True
  if_embed_poi: False
  
  batch_size: 128
  microbatch: 32
  log_interval: 10
  num_workers: 0
  
fp16:
  use_fp16: True


embedding:
  pre_train_embed: ./data/matrix/loc_embedding.pk
  hidden_dim: 128
  poi_dim: 32

diffusion:
  networkName: diffseq
  predict_xstart: True
  rescale_timesteps: True
  diffusion_steps: 2000
  noise_schedule: sqrt
  schedule_sampler: lossaware

  learned_mean_embed: True
  emb_scale_factor: 1.0
  denoise: True
  denoise_rate: 0.5
  rejection_rate: 0.0
  reg_rate: 0.0
  device: ""
  data_split_num: 0

  timestep_respacing: ""

model:
  # 
  num_encoder_layers: 2
  hidden_size: 768
  num_attention_heads: 12
  dropout: 0.1



optimiser:
  lr: 0.001
  weight_decay: 0.01
  ema_rate: 0.999
  gradient_clipping: 3
  # for loss
  # loss_weight: 0.1

  # for warmup
  warmup_epochs: 2
  decay_epochs: 0
  # for early stop
  early_stop_patience: 3
  early_stop_gamma: 0.1

dataset:
  data_dir: ./data/diff
  save_root: ./runs

  # data_dir: /cluster/scratch/hongy/generation/data/diff
  # save_root: /cluster/scratch/hongy/generation/runs