misc:
  dataset: mobis

  dataset_variation: all
  level: 14
  src_min_days: 14
  tgt_min_days: 7

  # normal
  clamping: False
  decoding_steps: 200
  decoding_rescaling_factor: 1
  # 
  split: test

  model_path: ./runs/base_ctx_150
  trained_model_name: model_ema_150.pt

  seed: 101
  
  batch_size: 256
  num_workers: 0

dataset:
  data_dir: ./data/diff
  save_root: ./runs