misc:
  dataset: mobis


  dataset_variation: small
  level: "10_13"
  src_min_days: 14
  tgt_min_days: 7

  # normal
  # clip_denoised: False
  # clamp_step: 500
  # step: 2000
  # DPM
  clip_denoised: False
  clamp: False
  step: 20
  start_n: 0
  # 
  split: test
  top_p: 0
  model_path: ./runs/mobis_diffseq_baseline_encode_long_seed110
  trained_model_name: model_ema_45.pt
  pre_train_embed: None # ./data/matrix/loc_embedding.pk

  # seq_len: 512
  max_location: 14883

  seed: 101
  
  batch_size: 128
  num_workers: 0
  
  networkName: diffseq
dataset:
  data_dir: ./data/diff
  save_root: ./runs