misc:
  dataset: mobis

  dataset_variation: all
  level: 13
  src_min_days: 14
  tgt_min_days: 7

  batch_size: 1
  num_workers: 0
  generate_len: 50
  top_k: 3
  debug: False
  verbose: True

  seed: 101
  # 
  if_embed_xy: False
  if_embed_poi: False
  if_include_duration: False
  if_include_mode: False

model:
  networkName: markov
  n_dependence: 1

dataset:
  data_dir: ./data/diff
  save_root: ./runs