misc:
  dataset: mobis

  dataset_variation: small
  level: "10_13"
  src_min_days: 14
  tgt_min_days: 7

  split: test
  use_pretrain: True
  pretrain_filepath: mobis_mhsa_1712332379
  model_name: model_14.pt
  generate_len: 50
  # 
  if_embed_time: False
  if_embed_user: False
  if_embed_poi: False
  if_embed_duration: False

  # 14882 + 1 for seperation
  max_location: 14883

  verbose: True
  debug: False
  batch_size: 64
  print_step: 50
  num_workers: 0

  use_fp16: True
  seed: 101
  

embedding:
  base_emb_size: 128
  poi_original_size: 16
  

model:
  networkName: mhsa
  # only for mhsa
  num_encoder_layers: 2
  nhead: 8

  fc_dropout: 0.1

optimiser:
  lr: 0.001
  weight_decay: 0.01
  # for loss
  loss_weight: 0.1
  # for warmup
  warmup_epochs: 3
  decay_epochs: 0
  # for decay
  patience: 3
  lr_gamma: 0.1

dataset:
  data_dir: ./data/diff
  save_root: ./runs