misc:
  dataset: mobis

  use_pretrain: False
  pretrain_filepath: mobis_mhsa_1698746890
  generate_len: 50
  # 
  if_embed_time: False
  if_embed_user: False
  if_embed_poi: False
  if_embed_duration: False

  verbose: True
  debug: False
  batch_size: 256
  print_step: 50
  num_workers: 0
  

embedding:
  base_emb_size: 64
  poi_original_size: 16

model:
  networkName: mhsa
  # only for mhsa
  num_encoder_layers: 2
  nhead: 4
  dim_feedforward: 128
  dropout: 0.1
  fc_dropout: 0.1

optimiser:
  optimizer: Adam
  max_epoch: 100
  lr: 0.001
  weight_decay: 0.000001
  # for loss
  loss_weight: 0.1
  # lr: 0.01
  # for Adam
  beta1: 0.9
  beta2: 0.999
  # for SGD
  momentum: 0.98
  # for warmup
  num_warmup_epochs: 2
  num_training_epochs: 50
  # for decay
  patience: 3
  lr_step_size: 1
  lr_gamma: 0.1

dataset:
  temp_save_root: ./data
  save_root: ./runs