misc:
  dataset: mobis_small

  use_pretrain: False
  pretrain_filepath: mobis_mhsa_1698746890
  generate_len: 50

  num_gen_samples: 25600
  # 
  if_embed_time: False
  if_embed_user: True
  if_embed_duration: False

  verbose: True
  debug: False
  batch_size: 64
  print_step: 30
  num_workers: 0
  

embedding:
  base_emb_size: 128
  hidden_dim: 64

model:
  networkName: movesim
  # only for mhsa
  task: attention
  periodic_loss: 3.0
  distance_loss: 1.5

optimiser:
  optimizer: Adam
  max_epoch: 4
  lr: 0.001
  weight_decay: 0.000001
  # lr: 0.01
  # for Adam
  beta1: 0.9
  beta2: 0.999
  # for SGD
  momentum: 0.98
  # for warmup
  num_warmup_epochs: 2
  num_training_epochs: 50
  # for decay
  patience: 3
  lr_step_size: 1
  lr_gamma: 0.1

dataset:
  temp_save_root: ./data
  save_root: ./runs