misc:
  dataset: mobis

  use_pretrain: False
  pretrain_filepath: mobis_movesim_pretrain_1699365477


  generate_len: 50
  previous_day: 28

  num_gen_samples: 12800
  # 
  if_embed_time: False
  if_embed_user: True
  if_embed_duration: False

  verbose: True
  debug: False
  d_batch_size: 128
  g_batch_size: 8
  print_step: 50
  num_workers: 0
  

embedding:
  base_emb_size: 128
  hidden_dim: 64

model:
  networkName: movesim
  #
  task: attention
  periodic_loss: 1.0
  distance_loss: 1.0

optimiser:
  optimizer: Adam
  max_epoch: 100
  adv_max_epoch: 30
  pre_lr: 0.0001
  d_lr: 0.00001
  g_lr: 0.0001
  weight_decay: 0.000001

  rollout_num: 4

  # for decay
  patience: 2
  lr_step_size: 1
  lr_gamma: 0.1

dataset:
  temp_save_root: ./data
  save_root: ./runs