misc:
  dataset: mobis

  use_pretrain: False
  pretrain_filepath: mobis_movesim_3


  generate_len: 50
  previous_day: 7

  num_gen_samples: 102400
  g_step: 1
  d_step: 2
  k_d: 2
  # 
  if_embed_time: False
  if_embed_user: True
  if_embed_duration: True

  verbose: True
  debug: False
  batch_size: 32
  print_step: 50
  num_workers: 0
  world_size: 1
  

embedding:
  base_emb_size: 64
  hidden_dim: 128

model:
  networkName: movesim
  #
  layer: 2
  head: 4
  task: attention
  periodic_loss: 0.5
  distance_loss: 0.5

optimiser:
  optimizer: Adam
  max_epoch: 100
  pre_lr: 0.001
  d_lr: 0.00001
  g_lr: 0.0001
  weight_decay: 0.000001

  loss_weight: 0.1

  rollout_num: 4

  # for decay
  patience: 3
  lr_gamma: 0.1

dataset:
  # temp_save_root: /cluster/scratch/hongy/generation/data
  # save_root: /cluster/scratch/hongy/generation/runs
  temp_save_root: ./data
  save_root: ./runs