misc:
  dataset: mobis

  use_pretrain: False
  pretrain_filepath: mobis_movesim_pretrain_1701698266


  generate_len: 50
  previous_day: 7

  num_gen_samples: 102400
  # 
  if_embed_time: False
  if_embed_user: True
  if_embed_duration: False

  verbose: True
  debug: False
  d_batch_size: 64
  g_batch_size: 32
  print_step: 10
  num_workers: 0
  

embedding:
  base_emb_size: 64
  hidden_dim: 256

model:
  networkName: movesim
  #
  task: attention
  periodic_loss: 0.5
  distance_loss: 0.5

optimiser:
  optimizer: Adam
  max_epoch: 100
  adv_max_epoch: 30
  pre_lr: 0.001
  d_lr: 0.00001
  g_lr: 0.0001
  weight_decay: 0.000001

  rollout_num: 1

  # for decay
  patience: 3
  lr_step_size: 1
  lr_gamma: 0.1

dataset:
  # temp_save_root: /cluster/scratch/hongy/generation/data
  # save_root: /cluster/scratch/hongy/generation/runs
  temp_save_root: ./data
  save_root: ./runs