misc:
  dataset: mobis

  dataset_variation: all
  level: 13
  src_min_days: 14
  tgt_min_days: 7

  split: train
  use_pretrain: True
  pretrain_filepath: mobis_movesim_pretrain

  generate_len: 50
  previous_day: 7

  num_gen_samples: 10240
  g_step: 1
  d_step: 4
  k_d: 2
  rollout_num: 4
  # 
  if_embed_time: False
  if_embed_poi: False
  if_embed_user: False
  if_include_duration: True
  if_include_mode: False

  # 14882 -> 14976 (28743 -> 28800)
  max_location: 14976  # 28800, 14976

  verbose: True
  debug: False
  batch_size: 128
  print_step: 50
  num_workers: 0
  world_size: 1

  use_fp16: True
  seed: 101

embedding:
  base_emb_size: 128
  hidden_dim: 128

model:
  networkName: movesim
  #
  layer: 2
  head: 8
  task: attention

optimiser:
  optimizer: Adam
  max_epoch: 100
  pre_lr: 0.001
  d_lr: 0.00001
  g_lr: 0.0001
  weight_decay: 0.01

  loss_weight: 0.1

  # for decay
  patience: 3
  lr_gamma: 0.1

dataset:
  # temp_save_root: /cluster/scratch/hongy/generation/data
  # save_root: /cluster/scratch/hongy/generation/runs
  data_dir: ./data/diff
  save_root: ./runs